---
# handlers file for ansible-role-k8s-basic

  handlers:
    - name: Yum clean
      command: yum clean all
      args: 
        warn: no

    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded